services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:5432:5432"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  app:
    build: #.
      dockerfile:
        ./Dockerfile-temp
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
    driver: local

networks:
  app-network:
    driver: host 
